const app=document.querySelector('#app'), balance=document.querySelector('#balance');
const questions=[
 ['Qual destas marcas de refrigerante você consome com mais frequência?',['Coca-Cola','Guaraná Antarctica','Pepsi','Fanta','Sprite']],
 ['Qual serviço de streaming você mais assiste no dia a dia?',['Netflix','Globoplay','Disney+','Max','Prime Video']],
 ['Qual marca de smartphone você escolheria hoje?',['Apple / iPhone','Samsung','Xiaomi','Motorola','Realme']],
 ['Qual rede de fast-food seria sua escolha?',["McDonald’s",'Burger King','Subway',"Habib’s",'Giraffas']],
 ['Em qual banco você prefere realizar suas operações?',['Nubank','Itaú','Inter','Bradesco','PicPay']]
]; const rewards=[305.50,326.30,298.40,334.60,320.20]; let screen='home', index=0, total=0, celebration=null;
function money(n){return n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function brandClass(name){return name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function brandLogo(name){const slugs={'Coca-Cola':'coca-cola','Guaraná Antarctica':'guarana-antarctica','Pepsi':'pepsi','Fanta':'fanta','Sprite':'sprite','Netflix':'netflix','Globoplay':'globoplay','Disney+':'disneyplus','Max':'max','Prime Video':'primevideo','Apple / iPhone':'apple','Samsung':'samsung','Xiaomi':'xiaomi','Motorola':'motorola','Realme':'realme','McDonald’s':'mcdonalds','Burger King':'burgerking','Subway':'subway','Habib’s':'habibs','Giraffas':'giraffas','Nubank':'nubank','Itaú':'itau','Inter':'inter','Bradesco':'bradesco','PicPay':'picpay'};const slug=slugs[name];return slug?`<span class="logo logo-image"><img src="https://cdn.simpleicons.org/${slug}" alt="Logo ${name}" /></span>`:'<span class="logo logo-empty" aria-hidden="true"></span>'}
function render(){
 if(screen==='home') app.innerHTML=`<section class="hero"><div class="kicker">Sua opinião. Sua torcida. Sua voz.</div><h1>Participe da <span>pesquisa</span></h1><p>Responda pesquisas sobre futebol, marcas e hábitos de consumo. Sua opinião ajuda a construir novas experiências para torcedores.</p><div class="card intro-card"><h2>Como funciona</h2><p>Cadastre-se, responda às perguntas e acompanhe a validação da sua participação.</p><div class="steps"><div class="step"><b>1</b>Cadastro</div><div class="step"><b>2</b>Perguntas</div><div class="step"><b>3</b>Validação</div><div class="step"><b>4</b>Pagamento</div></div><button class="btn" onclick="go('register')">COMEÇAR MINHA PARTICIPAÇÃO</button><p class="notice">O valor depende da elegibilidade e do regulamento.</p></div></section>`;
 if(screen==='register') app.innerHTML=`<div class="card"><div class="progress"><span>ETAPA 1 DE 4</span><b>Cadastro</b></div><div class="bar"><i style="width:25%"></i></div><h2>Cadastre-se para participar</h2><p>Usaremos estes dados somente para validar sua participação e entrar em contato. Consulte o regulamento antes de continuar.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input placeholder="Digite seu nome" /></div><div class="field"><label>WhatsApp</label><input placeholder="(00) 00000-0000" /></div><div class="field"><label>E-mail</label><input placeholder="voce@email.com" type="email" /></div></div><label class="check"><input type="checkbox" /> Li e aceito o regulamento e a política de privacidade da campanha.</label><br><button class="btn" onclick="go('fee')">CONCLUIR CADASTRO</button></div>`;
 if(screen==='fee') app.innerHTML=`<div class="card"><div class="progress"><span>ETAPA 2 DE 4</span><b>Manutenção da plataforma</b></div><div class="bar"><i style="width:50%"></i></div><div class="success-icon">✓</div><h2>Cadastro concluído</h2><p>Seu cadastro foi realizado. Para manter a plataforma ativa, atualizar as pesquisas e oferecer suporte aos participantes, existe uma taxa única de manutenção da plataforma.</p><div class="amount">R$ 14,50</div><button class="btn" onclick="go('payment')">PROSSEGUIR PARA O PAGAMENTO</button></div>`;
 if(screen==='payment') app.innerHTML=`<div class="card"><div class="progress"><span>ETAPA 3 DE 4</span><b>Pagamento</b></div><div class="bar"><i style="width:75%"></i></div><div class="success-icon">⌛</div><h2>Pagamento aguardando confirmação</h2><p>Conclua o pagamento da taxa de manutenção de <strong>R$ 14,50</strong> no provedor oficial. Após a confirmação automática, as pesquisas serão liberadas.</p><div class="status"><div><span>Valor</span><b>R$ 14,50</b></div><div><span>Status</span><b>AGUARDANDO</b></div></div><button class="btn" onclick="go('quiz')">CONTINUAR APÓS CONFIRMAÇÃO</button><p class="notice">A liberação deve ocorrer somente após a confirmação real do pagamento.</p></div>`;
 if(screen==='quiz'){let q=questions[index]; app.innerHTML=`<div class="card"><div class="progress"><span>ETAPA 4 DE 4 · PERGUNTA ${index+1} DE ${questions.length}</span><b>Valor estimado ${money(total)}</b></div><div class="bar"><i style="width:${(index+1)/questions.length*100}%"></i></div><h2 class="question">${q[0]}</h2><div class="options">${q[1].map((x,i)=>`<label class="option">${brandLogo(x)}<span class="option-name">${x}</span><input type="radio" name="q" onclick="answer(${i})" /></label>`).join('')}</div><p class="notice">Escolha uma opção para continuar. A participação e eventual remuneração seguem os critérios do regulamento.</p></div>`}
 if(screen==='done') app.innerHTML=`<div class="card success"><div class="success-icon">✓</div><div class="kicker">Pesquisa concluída</div><h2>Participação registrada!</h2><p>Suas respostas foram recebidas. O valor abaixo é uma estimativa sujeita à validação dos dados, à elegibilidade e aos critérios da campanha.</p><div class="amount">${money(total)}</div><div class="status"><div><span>Cadastro</span><b>CONCLUÍDO</b></div><div><span>Respostas</span><b>CONCLUÍDAS</b></div><div><span>Validação da equipe</span><b>EM ANÁLISE</b></div><div><span>Pagamento</span><b>APÓS APROVAÇÃO</b></div></div><button class="btn" onclick="go('contact')">ACOMPANHAR PARTICIPAÇÃO</button><p class="notice">Nossa equipe entrará em contato pelos dados cadastrados.</p></div>`;
 if(screen==='contact') app.innerHTML=`<div class="card success"><div class="success-icon">✓</div><div class="kicker">Acompanhamento confirmado</div><h2>Agora é só aguardar</h2><p>Nossa equipe entrará em contato com você pelos dados cadastrados para realizar o pagamento do valor acumulado pela sua participação.</p><div class="amount">${money(total)}</div><div class="status"><div><span>Status da participação</span><b>REGISTRADA</b></div><div><span>Pagamento</span><b>AGUARDANDO CONTATO</b></div></div><p class="notice">Mantenha seus dados de contato atualizados e consulte o regulamento para conhecer os prazos e as condições de pagamento.</p></div>`;
 if(celebration) app.insertAdjacentHTML('beforeend',`<div class="celebrate"><div class="celebrate-card"><div class="trophy">🏆</div><h2>Pesquisa concluída!</h2><p>Você recebeu um valor estimado de</p><div class="win-amount">${money(celebration)}</div><p>por esta pesquisa escolhida.</p><button class="btn" onclick="continueAfterWin()">CONTINUAR</button><p class="notice">Valor sujeito à validação e aos critérios da campanha.</p></div></div>`);
}
function go(s){screen=s;if(s==='quiz'){total=250;balance.textContent=money(total)}render();if(s==='contact'){setTimeout(()=>{confetti(72);burst(34)},80)}} function answer(){const earned=rewards[index];total+=earned;balance.textContent=money(total);balance.parentElement.classList.remove('pulse');void balance.offsetWidth;balance.parentElement.classList.add('pulse');celebration=earned;render();confetti();burst()} function continueAfterWin(){celebration=null;if(index<questions.length-1){index++;render()}else{screen='done';render()}} function confetti(count=26){for(let i=0;i<count;i++){const piece=document.createElement('i');piece.className='confetti';piece.style.setProperty('--x',`${Math.round((Math.random()-.5)*720)}px`);piece.style.setProperty('--y',`${Math.round(230+Math.random()*390)}px`);piece.style.animationDelay=`${Math.random()*.32}s`;piece.style.transform=`translate(-50%, -20px) rotate(${Math.random()*180}deg)`;document.body.appendChild(piece);setTimeout(()=>piece.remove(),1900)}} function burst(count=18){for(let i=0;i<count;i++){const p=document.createElement('i');p.className='burst';p.style.left=`${35+Math.random()*30}%`;p.style.top=`${35+Math.random()*20}%`;p.style.setProperty('--bx',`${Math.round((Math.random()-.5)*440)}px`);p.style.setProperty('--by',`${Math.round((Math.random()-.5)*300)}px`);document.body.appendChild(p);setTimeout(()=>p.remove(),900)}} render();
